---

- name: Install Apache
  apt: name=apache2 state=latest

- name: Disable default vhost
  file:
    path=/etc/apache2/sites-enabled/000-default.conf
    state=absent
  notify:
  - Reload Apache

- name: Install vagrant vhost
  template:
    src=vhost.conf.j2
    dest=/etc/apache2/sites-available/vagrant.conf

- name: Enable vagrant vhost
  file:
    src=/etc/apache2/sites-available/vagrant.conf
    dest=/etc/apache2/sites-enabled/vagrant.conf
    state=link
  notify:
  - Reload Apache
